name: 'CGFT Test Generation'
description:
  'An action to post test results or generate diff patches based on input'
author: 'CGFT'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  token:
    description: 'Github Token'
    required: true
  action:
    description: 'The action to perform'
    required: true
    default: 'post-tests'
    options:
      - 'post-tests'
      - 'apply-tests'

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: 'node12'
  main: 'dist/index.js'
